add support to list volumes based on metadata
gluster/glusterapi-python pull request #18
Opened 2018-07-23 07:00 UTC by Madhu-1

* if volume name is not present , list all volumes
* if name is present get that volume info
* if key, value are present, list volumes
based on key and value

Signed-off-by: Madhu Rajanna <mrajanna@redhat.com>

2018-07-23 07:28 UTC, sac-urs requested changes

2018-07-23 07:32 UTC, Madhu-1 commented on glusterapi/volume.py
>          if len(bricks) <= 0:
yeah, Thanks for pointing it out.

2018-07-23 07:38 UTC, sac-urs approved these changes
Looks good to me.

2018-07-24 06:51 UTC, devyanikota approved these changes

2018-07-24 06:51 UTC, devyanikota commented
+1

2018-07-24 06:51 UTC, merged

2018-07-24 14:42 UTC, Madhu-1 commented
@aravindavk please review